DELETE http://localhost:3003/api/blogs/69785f1349dac24255774dcb
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmVyaWVsIFRhbiIsInVzZXJuYW1lIjoiamVyaWVsdGFuIiwiaWF0IjoxNzY5NDk2OTEyfQ.o2f9LiAyMg9ZbMfcFL25xwyPcbE635QfocZUtTNS_5A