POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVG9tIFRhbiIsInVzZXJuYW1lIjoibWF0aG5lcmQiLCJpZCI6IjY5NzgzYjZmZDhkY2RjODE2NWZiYzllZSIsImlhdCI6MTc2OTQ5NTExMH0.ZpVjgyTrqE7MPKaWJ_Lr58af8UOyi4Zgm1OdI-3eJmM

{
    "title": "I sing",
    "author": "CS Lewis",
    "url": "abcde",
    "likes": 3
}